name: Rename Images

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-vision pillow gitpython

      - name: Verify JSON format
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | jq .

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Run image renaming script
        run: python image_renamer.py
        env:
          IMAGE_FOLDER: images/  # Optional：如果你的图像不是都在 'image/' 目录下

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Rename images based on Vision API" || echo "No changes to commit"
          git push
