name: Rename Images with AI

on:
  push:
    paths:
      - 'images/**'

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-vision pillow gitpython

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Rename images
        run: python .github/workflows/rename_images.py  # 确保路径正确

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # Add all changes under images/
          git add images/*

          # Attempt to commit, but if there are no changes, simply output a message
          if ! git commit -m "Rename images based on AI recognition"; then
            echo "No changes to commit"
          else
            # Get the branch name from the GITHUB_REF environment variable.
            BRANCH_NAME=${GITHUB_REF#refs/heads/}

            # Ensure the branch name isn't empty
            if [ -z "$BRANCH_NAME" ]; then
              echo "Error: Could not determine branch name from GITHUB_REF.  Falling back to 'main'."
              BRANCH_NAME="main"
            fi

            # Push the changes to the origin repository on the correct branch.
            git push origin HEAD:"$BRANCH_NAME"
          fi
