name: Rename Images with AI

on:
  push:
    paths:
      - 'images/**'

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-vision pillow gitpython

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Rename images
        run: python .github/workflows/rename_images.py

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add image/*
          git commit -m "Rename images based on AI recognition" || echo "No changes to commit"
          git push origin HEAD:main
